// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=.ts,valid_types=legacy_required+protovalidate_required"
// @generated from file random/v1/random.proto (package random.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file random/v1/random.proto.
 */
export const file_random_v1_random: GenFile = /*@__PURE__*/
  fileDesc("ChZyYW5kb20vdjEvcmFuZG9tLnByb3RvEglyYW5kb20udjEiLwoaR2VuZXJhdGVSYW5kb21CeXRlc1JlcXVlc3QSEQoJbnVtX2J5dGVzGAEgASgFIjMKG0dlbmVyYXRlUmFuZG9tQnl0ZXNSZXNwb25zZRIUCgxyYW5kb21fYnl0ZXMYASABKAwydwoNUmFuZG9tU2VydmljZRJmChNHZW5lcmF0ZVJhbmRvbUJ5dGVzEiUucmFuZG9tLnYxLkdlbmVyYXRlUmFuZG9tQnl0ZXNSZXF1ZXN0GiYucmFuZG9tLnYxLkdlbmVyYXRlUmFuZG9tQnl0ZXNSZXNwb25zZSIAYgZwcm90bzM");

/**
 * @generated from message random.v1.GenerateRandomBytesRequest
 */
export type GenerateRandomBytesRequest = Message<"random.v1.GenerateRandomBytesRequest"> & {
  /**
   * The number of random bytes to generate.
   *
   * @generated from field: int32 num_bytes = 1;
   */
  numBytes: number;
};

export type GenerateRandomBytesRequestValid = GenerateRandomBytesRequest;

/**
 * Describes the message random.v1.GenerateRandomBytesRequest.
 * Use `create(GenerateRandomBytesRequestSchema)` to create a new message.
 */
export const GenerateRandomBytesRequestSchema: GenMessage<GenerateRandomBytesRequest, {validType: GenerateRandomBytesRequestValid}> = /*@__PURE__*/
  messageDesc(file_random_v1_random, 0);

/**
 * @generated from message random.v1.GenerateRandomBytesResponse
 */
export type GenerateRandomBytesResponse = Message<"random.v1.GenerateRandomBytesResponse"> & {
  /**
   * The generated random bytes.
   *
   * @generated from field: bytes random_bytes = 1;
   */
  randomBytes: Uint8Array;
};

export type GenerateRandomBytesResponseValid = GenerateRandomBytesResponse;

/**
 * Describes the message random.v1.GenerateRandomBytesResponse.
 * Use `create(GenerateRandomBytesResponseSchema)` to create a new message.
 */
export const GenerateRandomBytesResponseSchema: GenMessage<GenerateRandomBytesResponse, {validType: GenerateRandomBytesResponseValid}> = /*@__PURE__*/
  messageDesc(file_random_v1_random, 1);

/**
 * @generated from service random.v1.RandomService
 */
export const RandomService: GenService<{
  /**
   * GenerateRandomBytes generates a specified number of random bytes.
   *
   * @generated from rpc random.v1.RandomService.GenerateRandomBytes
   */
  generateRandomBytes: {
    methodKind: "unary";
    input: typeof GenerateRandomBytesRequestSchema;
    output: typeof GenerateRandomBytesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_random_v1_random, 0);

