// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=.ts,valid_types=legacy_required+protovalidate_required"
// @generated from file dating-settings/v1/dating-settings.proto (package datingsettings.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dating-settings/v1/dating-settings.proto.
 */
export const file_dating_settings_v1_dating_settings: GenFile = /*@__PURE__*/
  fileDesc("CihkYXRpbmctc2V0dGluZ3MvdjEvZGF0aW5nLXNldHRpbmdzLnByb3RvEhFkYXRpbmdzZXR0aW5ncy52MSIUChJQbGFjZWhvbGRlclJlcXVlc3QiJgoTUGxhY2Vob2xkZXJSZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJMnUKFURhdGluZ1NldHRpbmdzU2VydmljZRJcCgtQbGFjZWhvbGRlchIlLmRhdGluZ3NldHRpbmdzLnYxLlBsYWNlaG9sZGVyUmVxdWVzdBomLmRhdGluZ3NldHRpbmdzLnYxLlBsYWNlaG9sZGVyUmVzcG9uc2ViBnByb3RvMw");

/**
 * Placeholder request message.
 *
 * @generated from message datingsettings.v1.PlaceholderRequest
 */
export type PlaceholderRequest = Message<"datingsettings.v1.PlaceholderRequest"> & {
};

export type PlaceholderRequestValid = PlaceholderRequest;

/**
 * Describes the message datingsettings.v1.PlaceholderRequest.
 * Use `create(PlaceholderRequestSchema)` to create a new message.
 */
export const PlaceholderRequestSchema: GenMessage<PlaceholderRequest, {validType: PlaceholderRequestValid}> = /*@__PURE__*/
  messageDesc(file_dating_settings_v1_dating_settings, 0);

/**
 * Placeholder response message.
 *
 * @generated from message datingsettings.v1.PlaceholderResponse
 */
export type PlaceholderResponse = Message<"datingsettings.v1.PlaceholderResponse"> & {
  /**
   * A simple message field.
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

export type PlaceholderResponseValid = PlaceholderResponse;

/**
 * Describes the message datingsettings.v1.PlaceholderResponse.
 * Use `create(PlaceholderResponseSchema)` to create a new message.
 */
export const PlaceholderResponseSchema: GenMessage<PlaceholderResponse, {validType: PlaceholderResponseValid}> = /*@__PURE__*/
  messageDesc(file_dating_settings_v1_dating_settings, 1);

/**
 * @generated from service datingsettings.v1.DatingSettingsService
 */
export const DatingSettingsService: GenService<{
  /**
   * Placeholder RPC method that does not perform any real operation.
   *
   * @generated from rpc datingsettings.v1.DatingSettingsService.Placeholder
   */
  placeholder: {
    methodKind: "unary";
    input: typeof PlaceholderRequestSchema;
    output: typeof PlaceholderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dating_settings_v1_dating_settings, 0);

