// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=.ts,valid_types=legacy_required+protovalidate_required"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiRgoMTG9naW5SZXF1ZXN0EhsKCHVzZXJuYW1lGAEgASgJQgm6SAZyBBACGDISGQoIcGFzc3dvcmQYAiABKAlCB7pIBHICEAgiLgoNTG9naW5SZXNwb25zZRIdCgxhY2Nlc3NfdG9rZW4YASABKAlCB7pIBHICEAUiDwoNTG9nb3V0UmVxdWVzdCIQCg5Mb2dvdXRSZXNwb25zZTKEAQoLQXV0aFNlcnZpY2USOAoFTG9naW4SFS5hdXRoLnYxLkxvZ2luUmVxdWVzdBoWLmF1dGgudjEuTG9naW5SZXNwb25zZSIAEjsKBkxvZ291dBIWLmF1dGgudjEuTG9nb3V0UmVxdWVzdBoXLmF1dGgudjEuTG9nb3V0UmVzcG9uc2UiAGIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * Request message for user login.
 *
 * @generated from message auth.v1.LoginRequest
 */
export type LoginRequest = Message<"auth.v1.LoginRequest"> & {
  /**
   * The username of the user
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * The password of the user
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

export type LoginRequestValid = LoginRequest;

/**
 * Describes the message auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest, {validType: LoginRequestValid}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * Response message for user login.
 *
 * @generated from message auth.v1.LoginResponse
 */
export type LoginResponse = Message<"auth.v1.LoginResponse"> & {
  /**
   * The access token issued upon successful login
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

export type LoginResponseValid = LoginResponse;

/**
 * Describes the message auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse, {validType: LoginResponseValid}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * Request message for user logout.
 *
 * @generated from message auth.v1.LogoutRequest
 */
export type LogoutRequest = Message<"auth.v1.LogoutRequest"> & {
};

export type LogoutRequestValid = LogoutRequest;

/**
 * Describes the message auth.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest, {validType: LogoutRequestValid}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * Response message for user logout.
 *
 * @generated from message auth.v1.LogoutResponse
 */
export type LogoutResponse = Message<"auth.v1.LogoutResponse"> & {
};

export type LogoutResponseValid = LogoutResponse;

/**
 * Describes the message auth.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse, {validType: LogoutResponseValid}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * Login allows a user to authenticate with their username and password.
   *
   * @generated from rpc auth.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Logout allows a user to terminate their session.
   *
   * @generated from rpc auth.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

