// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=.ts,valid_types=legacy_required+protovalidate_required"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEibQoMTG9naW5SZXF1ZXN0EhsKCHVzZXJuYW1lGAEgASgJQgm6SAZyBBADGDISGwoIcGFzc3dvcmQYAiABKAlCCbpIBnIEEAgYZBIjChBjb25maXJtX3Bhc3N3b3JkGAMgASgJQgm6SAZyBBAIGGQiHgoNTG9naW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCTJHCgtBdXRoU2VydmljZRI4CgVMb2dpbhIVLmF1dGgudjEuTG9naW5SZXF1ZXN0GhYuYXV0aC52MS5Mb2dpblJlc3BvbnNlIgBiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message auth.v1.LoginRequest
 */
export type LoginRequest = Message<"auth.v1.LoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string confirm_password = 3;
   */
  confirmPassword: string;
};

export type LoginRequestValid = LoginRequest;

/**
 * Describes the message auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest, {validType: LoginRequestValid}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.LoginResponse
 */
export type LoginResponse = Message<"auth.v1.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

export type LoginResponseValid = LoginResponse;

/**
 * Describes the message auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse, {validType: LoginResponseValid}> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

